name: CI
on:
  push:
    branches: [master, develop, alpha]
  pull_request:
    branches: [master, develop, alpha]

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        id: release-1
        uses: actions/checkout@v1

      - name: Setup Node.js
        id: release-3
        uses: actions/setup-node@v2.1.0
        with:
          node-version: "10.19.0"

      - name: Install Node.js dependencies
        id: release-4
        run: |
          npm ci

      - name: Build
        id: release-5
        run: |
          npm run build

      - name: Run Lighthouse
        id: release-7
        run: |
          npm run lighthouse

      - name: Run Tests
        id: release-8
        run: |
          npm run test

      - name: Release
        id: release-9
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm run release
