name: CI
on:
  push:
    branches: [master, develop, alpha]
  pull_request:
    branches: [master, develop, alpha]

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        id: build-1
        uses: actions/checkout@v1

      - name: Setup Node.js
        id: build-3
        uses: actions/setup-node@v2.1.0
        with:
          node-version: "10.19.0"

      - name: Install Node.js dependencies
        id: build-4
        run: |
          npm ci

      - name: Release
        id: build-5
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm run release
